server:
  port: 8080

spring:
  application:
    name: zuul-server

zuul:
  routes:
    user-service: /user-api/** # Call http://localhost:8080/user-api/users/

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
